extends: eslint-config-airbnb-base
rules:
  no-console: off
  import/extensions: off
  consistent-return: off
  no-plusplus: off
  no-useless-escape: off
  no-trailing-spaces: off
  no-else-return: off
  eqeqeq: off



